## cartridge.properties for cartridge int_llm_integration
#Sun Jan 19 10:00:00 CDT 2025
demandware.cartridges.int_llm_integration.id=int_llm_integration
demandware.cartridges.int_llm_integration.multipleLanguageStorefront=true
